# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0:

# We can not do multi-level includes, so we need to manually include all of
# our templates here
include:
  # projects using these templates should not need to pull the bootstrap
  - local: '/bootstrap/bootstrap.yml'

  # Debian container builder template
  - project: 'bentiss/ci-templates'
    ref: master
    file: '/templates/debian.yml'


variables:
  DEBIAN_VERSION: 'stretch'
  DEBIAN_DEBS: 'curl'
  DEBIAN_SCRIPT: 'test/debian.sh'


stages:
  - bootstrapping_check
  - bootstrapping
  - container_build
  - check
  - container_push


.debian:ci@container-build:
  extends: .debian@container-build
  # FIXME: temporary workaround to speed up development
  # we want to test the creation of the container with the new bootstrap image
  # image: $CI_REGISTRY_IMAGE/buildah:$CI_PIPELINE_ID
  image: $CI_REGISTRY_IMAGE/buildah:latest
  stage: container_build


debian:stretch@container-build:
  extends: .debian:ci@container-build
  variables:
    DEBIAN_VERSION: stretch


debian:buster@container-build:
  extends: .debian:ci@container-build
  variables:
    DEBIAN_VERSION: buster


.debian@check:
  stage: check
  script:
      # make sure curl has been installed
    - curl --insecure https://gitlab.freedesktop.org
      # make sure our test script has been run
    - if [[ -e /test_file ]] ;
      then
        echo $DEBIAN_SCRIPT properly run ;
      else
        exit 1 ;
      fi


debian:stretch@check:
  extends: .debian@check
  image: $CI_REGISTRY_IMAGE/debian/stretch:$CI_PIPELINE_ID


debian:buster@check:
  extends: .debian@check
  image: $CI_REGISTRY_IMAGE/debian/buster:$CI_PIPELINE_ID


bootstrap-push@push:
  stage: container_push
  image: $CI_REGISTRY_IMAGE/buildah:$CI_PIPELINE_ID
  script:
    # push the container image to the registry
    - skopeo copy docker://$CI_REGISTRY_IMAGE/buildah:$CI_PIPELINE_ID docker://$CI_REGISTRY_IMAGE/buildah:latest
  variables:
    GIT_STRATEGY: none
  # FIXME: temporary workaround to speed up development
  when: manual
