# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0:

# We can not do multi-level includes, so we need to manually include all of
# our templates here
include:
  # projects using these templates should not need to pull the bootstrap
  - local: '/bootstrap/bootstrap.yml'

  # Debian container builder template
  # projects using this should reference this with the following:
  #
  # - project: 'bentiss/ci-templates'
  #   ref: master # or git sha, see https://docs.gitlab.com/ee/ci/yaml/#includefile
  #   file: '/templates/debian.yml'
  #
  - local: '/templates/debian.yml'

  # Fedora container builder template
  - local: '/templates/fedora.yml'


variables:
  DEBIAN_DEBS: 'curl'
  DEBIAN_SCRIPT: 'test/debian.sh'
  FEDORA_RPMS: 'wget'
  FEDORA_SCRIPT: 'test/debian.sh'


stages:
  - bootstrapping_check
  - bootstrapping
  - container_build
  - check
  - container_push


.debian:ci@container-build:
  extends: .debian@container-build
  # FIXME: temporary workaround to speed up development
  # we want to test the creation of the container with the new bootstrap image
  # image: $CI_REGISTRY_IMAGE/buildah:$CI_PIPELINE_ID
  image: $CI_REGISTRY_IMAGE/buildah:latest
  stage: container_build


.debian:ci@container-ifnot-exists:
  extends: .debian@container-ifnot-exists
  # FIXME: temporary workaround to speed up development
  # we want to test the creation of the container with the new bootstrap image
  # image: $CI_REGISTRY_IMAGE/buildah:$CI_PIPELINE_ID
  image: $CI_REGISTRY_IMAGE/buildah:latest
  stage: container_build


debian:stretch@container-build:
  extends: .debian:ci@container-build
  variables:
    DEBIAN_VERSION: stretch


debian:stretch-backports@container-build:
  extends: .debian:ci@container-build
  variables:
    DEBIAN_VERSION: stretch
    DEBIAN_USE_BACKPORTS: 'true'
    DEBIAN_DEBS: 'gnupg'


debian:stretch@container-ifnot-exists:
  extends: .debian:ci@container-ifnot-exists
  variables:
    UPSTREAM_REPO: bentiss/ci-templates
    DEBIAN_VERSION: stretch
    DEBIAN_TAG: immutable_tag


debian-forced:stretch@container-ifnot-exists:
  extends: .debian:ci@container-ifnot-exists
  variables:
    UPSTREAM_REPO: bentiss/ci-templates
    DEBIAN_VERSION: stretch
    DEBIAN_TAG: $CI_PIPELINE_IID


debian:buster@container-build:
  extends: .debian:ci@container-build
  variables:
    DEBIAN_VERSION: buster


.debian@check:
  stage: check
  script:
      # make sure curl has been installed
    - curl --insecure https://gitlab.freedesktop.org
      # make sure our test script has been run
    - if [[ -e /test_file ]] ;
      then
        echo $DEBIAN_SCRIPT properly run ;
      else
        exit 1 ;
      fi


debian:stretch@check:
  extends: .debian@check
  image: $CI_REGISTRY_IMAGE/debian/stretch:$CI_PIPELINE_ID


debian:stretch-backports@check:
  extends: .debian@check
  image: $CI_REGISTRY_IMAGE/debian/stretch:$CI_PIPELINE_ID
  script:
      # make sure gnupg 2.2 has been installed
    - |
     [[ x"$(gpg --version | head -n 1 | awk '{ print $3; }')" > x"2.2" ]] && echo gnupg 2.2.x has been installed


debian:buster@check:
  extends: .debian@check
  image: $CI_REGISTRY_IMAGE/debian/buster:$CI_PIPELINE_ID


debian:ifnot-exists@check:
  extends: .debian@check
  image: $CI_REGISTRY_IMAGE/debian/stretch:immutable_tag


debian:forced-ifnot-exists@check:
  extends: .debian@check
  image: $CI_REGISTRY_IMAGE/debian/stretch:$CI_PIPELINE_IID


.fedora:ci@container-build:
  extends: .fedora@container-build
  # FIXME: temporary workaround to speed up development
  # we want to test the creation of the container with the new bootstrap image
  # image: $CI_REGISTRY_IMAGE/buildah:$CI_PIPELINE_ID
  image: $CI_REGISTRY_IMAGE/buildah:latest
  stage: container_build


.fedora:ci@container-ifnot-exists:
  extends: .fedora@container-ifnot-exists
  # FIXME: temporary workaround to speed up development
  # we want to test the creation of the container with the new bootstrap image
  # image: $CI_REGISTRY_IMAGE/buildah:$CI_PIPELINE_ID
  image: $CI_REGISTRY_IMAGE/buildah:latest
  stage: container_build


fedora:29@container-build:
  extends: .fedora:ci@container-build
  variables:
    FEDORA_VERSION: 29


fedora:rawhide@container-build:
  extends: .fedora:ci@container-build
  variables:
    FEDORA_VERSION: rawhide


fedora:rawhide@container-ifnot-exists:
  extends: .fedora:ci@container-ifnot-exists
  variables:
    UPSTREAM_REPO: bentiss/ci-templates
    FEDORA_VERSION: rawhide
    FEDORA_TAG: immutable_tag


fedora-forced:rawhide@container-ifnot-exists:
  extends: .fedora:ci@container-ifnot-exists
  variables:
    UPSTREAM_REPO: bentiss/ci-templates
    FEDORA_VERSION: rawhide
    FEDORA_TAG: $CI_PIPELINE_IID


.fedora@check:
  stage: check
  script:
      # make sure wget has been installed
    - wget https://gitlab.freedesktop.org
      # make sure our test script has been run
    - if [[ -e /test_file ]] ;
      then
        echo $FEDORA_SCRIPT properly run ;
      else
        exit 1 ;
      fi


fedora:29@check:
  extends: .fedora@check
  image: $CI_REGISTRY_IMAGE/fedora/29:$CI_PIPELINE_ID


fedora:rawhide@check:
  extends: .fedora@check
  image: $CI_REGISTRY_IMAGE/fedora/rawhide:$CI_PIPELINE_ID


bootstrap-push@push:
  stage: container_push
  image: $CI_REGISTRY_IMAGE/buildah:$CI_PIPELINE_ID
  script:
    # push the container image to the registry
    - skopeo copy docker://$CI_REGISTRY_IMAGE/buildah:$CI_PIPELINE_ID docker://$CI_REGISTRY_IMAGE/buildah:latest
  variables:
    GIT_STRATEGY: none
  # FIXME: temporary workaround to speed up development
  when: manual
